version: "{build}"
image: Visual Studio 2017
pull_requests:
  do_not_increment_build_number: true
shallow_clone: true

install:
- cmd: >-
    set QTDIR=C:\Qt\5.12\msvc2017_64

    set PATH=%PATH%;%QTDIR%\bin

    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
build_script:
- cmd: >-
    dir

    mkdir build

    cd build

    qmake ../fuel.pro

    set cl=/MP

    nmake /S /NOLOGO

    windeployqt release/fuel.exe --release --no-compiler-runtime --no-translations --no-opengl-sw --dir fuel-scm/

    cp release/fuel.exe fuel-scm/

artifacts:
- path: build/fuel-scm
  name: fuel-scm
