set(RES_DIR "${tabler_icons_SOURCE_DIR}/png")
file(GLOB_RECURSE FILLED_ICONS LIST_DIRECTORIES false "${RES_DIR}/filled/*")
file(GLOB_RECURSE OUTLINE_ICONS LIST_DIRECTORIES false "${RES_DIR}/outline/*")

###############################
# Generate resources_autogenerated.qrc
###############################
message(STATUS "Generating resources_autogenerated.qrc")

foreach (_file ${FILLED_ICONS})
    cmake_path(GET _file STEM FILE_NAME)
    list(APPEND RES_RESOURCES_CONTENT "    <file alias=\"${FILE_NAME}-f\">${_file}</file>")
endforeach ()

foreach (_file ${OUTLINE_ICONS})
    cmake_path(GET _file STEM FILE_NAME)
    list(APPEND RES_RESOURCES_CONTENT "    <file alias=\"${FILE_NAME}\">${_file}</file>")
endforeach ()

list(JOIN RES_RESOURCES_CONTENT "\n" RES_RESOURCES_CONTENT)
configure_file(${CMAKE_CURRENT_LIST_DIR}/resources_autogenerated.qrc.in ${CMAKE_SOURCE_DIR}/rsrc/resources_autogenerated.qrc @ONLY)