---
name: Build

on: [push, pull_request]

jobs:
  build-msvc:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Add Conan to path
        run: echo "C:\Program Files\Conan\conan\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Install deps
        run: choco install jom conan -y

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.10.0

      - name: Cache conan packages
        uses: actions/cache@v2.1.7
        with:
          key: win-conan-${{ hashFiles('**/conanfile.txt') }}
          path: ~/.conan/

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2.1.7
        with:
          path: "${{ github.workspace }}/qt/"
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          modules: qtwebengine
          dir: "${{ github.workspace }}/qt/"

      - name: Export qtkeychain
        run: |
          conan export recipes/qtkeychain

      - name: Build
        run: |
          mkdir build
          cd build
          conan install .. --build=missing
          cmake -G"NMake Makefiles JOM" -DCMAKE_INSTALL_PREFIX=redist ..
          jom
        shell: cmd

      - name: Install
        run: |
          cd build
          jom install
        shell: cmd

      - name: Upload redist folder
        uses: actions/upload-artifact@v2
        with:
          name: fuel-win
          path: build/redist

  build-gcc:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Install qt
        run: |
          sudo apt-get update
          sudo apt-get install qt5keychain-dev qtwebengine5-dev qttools5-dev -y

      - name: Build
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          make -j4
        shell: bash