---
name: Build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
    env:
      BUILD_TOOLS_PATH: C:\apps\build-tools\
    steps:
      - run: echo $env:BUILD_TOOLS_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install Build tools
        if: startsWith(matrix.os, 'windows')
        shell: cmake -P {0}
        run: |
          file(MAKE_DIRECTORY $ENV{BUILD_TOOLS_PATH})
          file(DOWNLOAD https://cdn.anotherfoxguy.com/build-tools.zip "$ENV{TMP}/build-tools.zip" SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xzf "$ENV{TMP}/build-tools.zip" WORKING_DIRECTORY "$ENV{BUILD_TOOLS_PATH}")

      - name: Install dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get -y install ninja-build
          curl "https://git.anotherfoxguy.com/AnotherFoxGuy/install-scripts/raw/branch/main/install-conan.sh" | sudo bash

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.0

      - name: Cache conan packages
        uses: actions/cache@v3
        with:
          key: conan-${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}
          path: ~/.conan/

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/qt/"
          key: ${{ runner.os }}-QtCache

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          aqtversion: '==2.1.0'
          version: 6.4.0
          modules: qt5compat qtpositioning qtwebchannel qtwebengine qtwebview
          dir: "${{ github.workspace }}/qt/"

      - name: Add conan remote
        run: conan remote add AFG https://conan.anotherfoxguy.com -f

      - name: Build
        run: |
          mkdir build
          cd build
          conan install .. --build=missing
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=redist ..
          ninja

      - name: Install
        run: |
          cd build
          ninja install

      - name: Upload redist folder
        uses: actions/upload-artifact@v3
        with:
          name: fuel-${{ runner.os }}
          path: build/redist
